week1/BOJ_1012_유기농배추/seokjun.py

✨feat: BOJ_1012_유기농배추 seokjun

---

week1/BOJ_1916_최소비용구하기/seokjun_1916.py
week1/BOJ_2468_안전영역/seokjun_2468.js
week1/BOJ_2468_안전영역/seokjun_2468.py

seokjun_1916.py
**_커밋 실수로 다시 올림_**
--------------------------------------------------
seokjun_2468.py
파이썬 버전
seokjun_2468.js
자바스크립트 버전

 [240905] BOJ_2468__안전영역 seokjun

---

week1/BOJ_10026_적록색약/jinsoo_bfs.py
week1/BOJ_7576_토마토/jinsoo.py

[240905] BOJ 토마토 - jinsoo

---

.gitignore
week1/BOJ_10026_적록색약/seokjun_10026.js
week1/BOJ_10026_적록색약/seokjun_10026.py

[240909] BOJ 적록색약 문제 풀이 - seokjun

---

week2/BOJ_16236_아기상어/seokjun.py
week2/BOJ_1926_그림/seokjun.py
week2/BOJ_2178_미로탐색/seokjun.py

week2 BOJ 문제 풀이
1. 미로탐색
2. 그림
3. 아기상어

[240914] week2 BOJ 3문제 풀이 - 석준

---

week2/BOJ_1926_그림/jinsoo.py

[240917] BOJ 그림 - 진수

---

week2/BOJ_16236_아기상어/eunji.py

[240916] BOJ 아기상어 문제풀이 - 은지

---

week2/BOJ_16236_아기상어/gaguriee.py

[240918] BOJ 아기상어 알고리즘 문제 풀이 - 가경

---

week3/BOJ_15486_퇴사2/jinsoo.py

[240920] BOJ 퇴사2 - 진수

---

week3/BOJ_11049_행렬곱셈순서/jinsoo.py

[240919] BOJ 행렬곱셈순서 - 파이썬 시간초과 pypy3 통과

---

week3/BOJ_11049_행렬곱셈순서/seokjun.py
week3/BOJ_15486_퇴사2/seokjun.py

행렬곱셈순서 문제 - 점화식을 어떻게 세워야할까요? ?  ?

[240920] BOJ 행렬곱셈순서 - 실패

---

week3/BOJ_9252_LCS2/jinsoo.py

[240921] BOJ LCS2 - jinsoo 답안 참조

---

week3/BOJ_11276_2xN타일링/seokjun.py
week3/BOJ_2579_계단오르기/seokjun.py

BOJ 계단오르기, 2xN 타일링 풀이 - seokjun

---

week3/BOJ_11276_2xN타일링/eunji.py
week3/BOJ_2579_계단오르기/eunji.py

2xn 타일링 하나 맞았다!!!! DP 넘 어려워!!!!!!!!!!

[240923] BOJ 계단오르기, 2xn 타일링 알고리즘 문제풀이

---

week3/BOJ_11276_2xN타일링/gaguriee.py
week3/BOJ_2579_계단오르기/gaguriee.py

BOJ 계단오르기 89%에서 틀려서 답안 참고
했더니 너무 easy하게 풀더라고..!!!! 하하하하하

[240923] 2xn 타일링, BOJ 계단오르기 알고리즘 문제풀이

---

week4/BOJ-14267-회사_문화_1/gaguriee.py
week5/BOJ_11722_가장긴감소하는부분수열/gaguriee.py
week5/BOJ_2156_포도주시식/gaguriee.py

✨feat: BOJ_2156_포도주시식 알고리즘 구현

---

week5/BOJ_9251_LCS/gaguriee.py

[241004] BOJ LCS 문제풀이 - 가경

---

week5/BOJ_1966_프린터큐/eunji.py

[241007] BOJ 프린터큐 알고리즘 문제풀이 - 은지

---

week5/BOJ_11722_가장긴감소하는부분수열/jinsoo.py
week5/BOJ_1966_프린터큐/jinsoo.py
week5/BOJ_2156_포도주시식/jinsoo.py
week5/BOJ_9251_LCS/jinsoo.py

[241007] BOJ 4문제 - 파이썬으로 풀이

---

week5/BOJ_1966_프린터큐/seokjun.py

[241007] BOJ 프린터큐 알고리즘 문제풀이 - 석준

---

week6/COD_마법의숲탐색/seokjun.js
week6/COD_마법의숲탐색/seokjun.py

[241012] 마법의 숲 탐색 풀이 - seokjun

---

week6/COD_마법의숲탐색/eunji.py

[241013] COD 마법의숲탐색 문제풀이 - 은지 

---

week6/COD_고대문명유적탐사/seokjun,.js

[241014] COD_고대문명유적탐사 풀이 - seokjun

---

week6/COD_마법의숲탐색/gaguriee.py

[241013] COD 마법의숲탐색 문제풀이 - 가경

---

week6/COD_고대문명유적탐사/eunji.py

[241014] COD 고대문명유적탐사 - 은지

---

week7/PGS_모의고사/eunji.py
week7/PGS_모의고사/gaguriee.py
week7/PGS_소수찾기/gaguriee.py
week7/PGS_최소직사각형/eunji.py
week7/PGS_최소직사각형/gaguriee.py

[241015]PGS 완전탐색 최소직사각형, 모의고사 문제풀이 - 은지

---

week7/PGS_전력망을둘로나누기/eunji.py
week7/PGS_피로도/eunji.py

[241018] PGS 피로도, 전력망을둘로나누기 문제풀이 - 은지

---

Programmers/Greedy/체육복/eunji.py

[241022] PGS 체육복 문제풀이 - 은지
